### ISSUE TITLE
`Error in base::nchar(wide_chars$test, type = "width")` in `nba_example/download_nba_example_data.R`

### ISSUE THREAD

**Issue by Aytijhya** [shinjaehyeok/e_detector_paper#1]
In the file `nba_example/download_nba_example_data.R`, the line 
```
T_gamelog_reg <- suppressWarnings(game_logs(seasons = selectedSeasons, league = "NBA", result_types = "team", season_types = "Regular Season"))
```

is showing the following error:

```
Error in base::nchar(wide_chars$test, type = "width") : 
  promise already under evaluation: recursive default argument reference or earlier problems?
```
I request the developers to kindly look into the matter and help me to fix the problem.

**Comment by shinjaehyeok** [comment]
This download script is working in my environment.

I'd recommend you reinstall nbastatR package and update all dependencies. If the problem still exists, please contact the developer of nbastatR package to resolve it.
